version: '3.1'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d  # 컨테이너가 시작되면 이 폴더 안에 있는 sh, sql 파일을 실행한다.
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=local
      - MYSQL_PASSWORD=asdf1234
      - MYSQL_ROOT_PASSWORD=asdf1234
      - TZ=Asia/Seoul
